version: '3.8'

services:
  zobot-app:
    image: hvidigaljr/zobot-app:latest
    ports:
      - "80:80"
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.zobot_app.rule=Host(`meu.zobot.top`)
        - traefik.http.routers.zobot_app.entrypoints=websecure
        - traefik.http.routers.zobot_app.tls.certresolver=letsencryptresolver
        - traefik.http.services.zobot_app.loadbalancer.server.port=80
        - traefik.http.services.zobot_app.loadbalancer.passHostHeader=true
        - traefik.http.routers.zobot_app.service=zobot_app
    environment:
      - VITE_SUPABASE_URL=https://oovwvznxynyzqwjkvoxn.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vdnd2em54eW55enF3amt2b3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Nzk3MjUsImV4cCI6MjA2MTQ1NTcyNX0.wBtJm5I8-TUyTbcWsx0tG4IDIsnmzyV_afKMNCm-oVM

networks:
  portainer:
    external: true
    name: portainer
